version: '3.8'
services:
  miniflux:
    image: miniflux/miniflux:2.0.21
    networks:
      - routing
      - miniflux
    depends_on:
      - db
    env_file:
      - miniflux.credentials
    environment:
      - DATABASE_URL=postgres://miniflux:secret@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - POLLING_FREQUENCY=60
      - CREATE_ADMIN=1
    restart: unless-stopped
    volumes:
      - type: volume
        source: routing
        target: /miniflux
        bind:
          propagation: rshared
      - type: bind
        source: ./data/miniflux/nginx.conf
        target: /miniflux/miniflux/nginx.conf
        bind:
          propagatin: rshared
  db:
    image: postgres:10.1
    networks:
      - miniflux
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
    volumes:
      - miniflux-db:/var/lib/postgresql/data
  rsshub:
    image: diygod/rsshub
    networks:
      - routing
      - rsshub
    restart: always
    volumes:
      - type: volume
        source: routing
        target: /rsshub
        bind:
          propagation: rshared
      - type: bind
        source: ./data/rsshub/nginx.conf
        target: /rsshub/rsshub/nginx.conf
        bind:
          propagatin: rshared
    environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: 'redis://redis:6379/'
      PUPPETEER_WS_ENDPOINT: 'ws://browserless:3000'
    depends_on:
    - redis
    - browserless
  browserless:
    image: browserless/chrome
    networks:
      - rsshub
    restart: always
  redis:
    image: redis:alpine
    networks:
      - rsshub
    restart: always
    volumes:
      - redis:/data
networks:
  routing:
    external:
      name: routing-hooked
  miniflux:
  rsshub:
volumes:
  miniflux-db:
  redis:
  routing:
    external:
      name: routing-hooked
