version: '3.8'
services:
  miniflux:
    image: miniflux/miniflux:2.0.21
    networks:
      - nginx
      - miniflux
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://miniflux:secret@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - POLLING_FREQUENCY=60
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=miniflux
      - ADMIN_PASSWORD=miniflux@2020
    restart: unless-stopped
    volumes:
      - nginx:/etc/nginx.h
      - ./data/miniflux.conf:/etc/nginx.h/miniflux.conf
  db:
    image: postgres:10.1
    networks:
      - miniflux
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
    volumes:
      - miniflux-db:/var/lib/postgresql/data
networks:
  nginx:
    external:
      name: v2ray-hooked
  miniflux:
volumes:
  miniflux-db:
  nginx:
    external:
      name: v2ray-hooked
